## GETTING STARTED WITH PYTORCH FUNDAMENTALS

#### **INSTALLATION**

In [1]:
## install pytorch for cpu
#!pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

In [2]:
import torch

In [3]:
# test pytorch
mat = torch.randn(5, 3)
print(mat)

tensor([[ 0.0515, -0.6171, -1.6786],
        [-0.2443,  1.3113, -1.0063],
        [ 0.4660, -1.4991,  1.2409],
        [ 1.2118, -0.3569,  0.1120],
        [ 0.2902,  1.2735,  1.4609]])


## Introduction to Tensors

### Creating Tensors
- **Scalar**
- **Vector**
- **Matrix**
- **Tensor**

and performing methods on them

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim # scalar has 0-dimensions

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# vector: has magnitude (how far) and direction (which way)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                          [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
 TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

> up there, we've got a 1 three by three tensor </br>
> Naming convention: scalar and vector: lower case vars, matrix and tensors: UPPER CASE VARS

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update`

- `randn`: random numbers from a standard normal distribution with mean of 0 and variance of 1
- `rand` : random numbers from a uniform distribtion

In [32]:
# Create a random tensor of size (3, 4)
# command: torch.rand
random_uniform_tensor = torch.rand(3, 4)
random_uniform_tensor

tensor([[0.6781, 0.2159, 0.2513, 0.1991],
        [0.3863, 0.6774, 0.4013, 0.8482],
        [0.6696, 0.2562, 0.2134, 0.9965]])

In [34]:
random_normal_tensor = torch.randn(size=(5, 5))
random_normal_tensor

tensor([[ 0.7675, -0.4729,  0.1072, -1.1738,  0.8230],
        [-1.0236, -0.2564, -1.7991, -0.4644,  0.7873],
        [ 2.2873,  0.4438,  0.1758,  0.7317,  1.6506],
        [ 1.2289, -0.3931,  0.5512, -1.0404,  0.9965],
        [-0.0105, -1.3731,  1.2013, -1.9179,  0.8289]])

In [35]:
# Create a random tensor with similar shape to an image tensor
random_iamge_size_tensor = torch.rand(size=(3, 224, 224)) # color channels, height: cc (R, G, B)
random_iamge_size_tensor.shape, random_iamge_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [36]:
random_tensor_exercise = torch.rand(10, 10, 10)
random_tensor_exercise

tensor([[[6.2802e-01, 7.6671e-01, 8.9174e-01, 7.5395e-01, 6.4430e-01,
          9.8630e-01, 8.9113e-01, 2.9599e-01, 2.5878e-01, 5.9774e-01],
         [7.3839e-02, 9.5974e-01, 1.4574e-01, 4.6520e-02, 7.9236e-01,
          8.3975e-01, 5.2730e-01, 8.1905e-01, 7.6047e-01, 7.8013e-01],
         [4.4943e-01, 9.6972e-01, 4.2694e-01, 1.2027e-01, 5.7368e-02,
          7.5022e-01, 4.5652e-01, 6.5297e-01, 1.3387e-01, 6.1129e-01],
         [5.0289e-01, 1.3171e-01, 6.2212e-01, 6.1783e-01, 7.1637e-01,
          6.9476e-01, 1.9241e-01, 7.4247e-01, 9.9520e-01, 8.4152e-01],
         [5.5731e-01, 6.6387e-01, 5.0624e-01, 1.8758e-01, 3.2410e-01,
          2.0989e-01, 1.8704e-01, 1.6154e-01, 3.0437e-01, 2.6030e-01],
         [9.2557e-01, 5.0748e-02, 3.1416e-01, 9.6015e-01, 2.7536e-01,
          8.5821e-01, 3.5592e-01, 3.7755e-01, 1.2532e-01, 5.0863e-01],
         [4.3579e-01, 8.8954e-01, 9.4822e-01, 4.2659e-01, 5.8157e-01,
          2.4745e-01, 5.9061e-01, 8.7841e-01, 6.8116e-02, 1.2341e-01],
         [5.9

### Zeros and Ones

In [37]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
# Crate a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype # default data type is always float unless explicitly specified

torch.float32

### Creating a range of tensors and tensors-like

returns a 1-D tensor containing a sequence of evenly spaced values within a specified interval (start (inclusive) and end (which is exclusive of the range))

For the range, a step size can be specified to dictate the gap between each value

In [41]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# Use torch.arange()
zero_to_1000 = torch.arange(start=0, end=1000, step=77)
zero_to_1000

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

**_like** suffix is used to create a tensor that mimics the property of another tensor
- `zeros_like`: creates a tensor filled with zeros
- `ones_like`: creates a tensor filled with ones
- `full_like`: creates a tensor filled with a specific scalar value
- `rand_like`: creates a tensor filled with random numbers from a uniform distribution of floating points
- `randn_like`: creates a tensor filled with random numbers from a normal distribution of floating points

In [59]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [61]:
ten_fulls = torch.full_like(one_to_ten, 7)  # specify any number other than one/zero
ten_fulls

tensor([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [63]:
ten_normals = torch.randn_like(one_to_ten)
ten_normals

NotImplementedError: "normal_kernel_cpu" not implemented for 'Long'

In [65]:
ten_uniforms = torch.rand_like(one_to_ten)
ten_uniforms

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

The above implementations didn't work because one_to_ten has data type Long/int32 but rand_like and randn_like create of data type float

### Tensor datatypes

**3 big errors when dealing with Tensor data types**
- Tensor not the right datatype
- Tensor not the right shape
- Tensor not the right device

In [70]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = None)

float_32_tensor

tensor([3., 6., 9.])

In [71]:
float_32_tensor.dtype

torch.float32

In [72]:
int_64_tensor = torch.tensor([3, 6, 9],
                              dtype = None)

int_64_tensor

tensor([3, 6, 9])

In [73]:
int_64_tensor.dtype

torch.int64

In [86]:
# change dtype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = None)

float_16_tensor = torch.tensor([3., 6., 9.],
                              dtype=torch.float16)

In [87]:
float_16_tensor.dtype

torch.float16

In [88]:
# adding the device and requires_grad parameters
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = None,             # data type of the tensor
                              device = None,            # cpu or cuda, default is None
                              requires_grad = False)    # 

float_32_tensor

tensor([3., 6., 9.])

In [89]:
# convert datatypes
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting Tensor Attributes