## GETTING STARTED WITH PYTORCH FUNDAMENTALS

#### **INSTALLATION**

In [109]:
## install pytorch for cpu
#!pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

In [1]:
import torch

In [19]:
# test pytorch
mat = torch.randn(5, 3)
print(mat)

tensor([[-0.2400, -1.8419,  0.2602],
        [ 0.4732,  0.4375,  0.4105],
        [ 0.6685, -0.3682, -0.5911],
        [ 0.5457,  0.3330,  0.8482],
        [ 0.0763, -0.5451, -0.3724]])


## Introduction to Tensors

### Creating Tensors
- **Scalar**
- **Vector**
- **Matrix**
- **Tensor**

and performing methods on them

In [20]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [21]:
scalar.ndim # scalar has 0-dimensions

0

In [22]:
# Get tensor back as Python int
scalar.item()

7

In [23]:
# vector: has magnitude (how far) and direction (which way)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [24]:
vector.ndim

1

In [25]:
vector.shape

torch.Size([2])

In [26]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [27]:
MATRIX.ndim

2

In [28]:
MATRIX.shape

torch.Size([2, 2])

In [29]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                          [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [30]:
 TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

> up there, we've got a 1 three by three tensor </br>
> Naming convention: scalar and vector: lower case vars, matrix and tensors: UPPER CASE VARS

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update`

- `randn`: random numbers from a standard normal distribution with mean of 0 and variance of 1
- `rand` : random numbers from a uniform distribtion

In [32]:
# Create a random tensor of size (3, 4)
# command: torch.rand
random_uniform_tensor = torch.rand(3, 4)
random_uniform_tensor

tensor([[0.8958, 0.7338, 0.9924, 0.0093],
        [0.7619, 0.9059, 0.2539, 0.1383],
        [0.5298, 0.8184, 0.3993, 0.0039]])

In [33]:
random_normal_tensor = torch.randn(size=(5, 5))
random_normal_tensor

tensor([[-0.7990, -1.9713,  1.1414, -0.5815, -1.4360],
        [ 1.3199,  0.1922, -0.5473, -0.4085, -0.6550],
        [ 1.9260,  0.2490, -0.8559, -1.0544,  2.2100],
        [-1.0305,  1.0698, -2.4525,  1.2597,  0.7430],
        [ 0.6590,  0.9066, -1.4568,  0.4967, -1.4164]])

In [34]:
# Create a random tensor with similar shape to an image tensor
random_iamge_size_tensor = torch.rand(size=(3, 224, 224)) # color channels, height: cc (R, G, B)
random_iamge_size_tensor.shape, random_iamge_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [35]:
random_tensor_exercise = torch.rand(10, 10, 10)
random_tensor_exercise

tensor([[[0.9441, 0.6544, 0.0702, 0.8174, 0.4188, 0.0474, 0.9967, 0.1033,
          0.3829, 0.2873],
         [0.7497, 0.7870, 0.8855, 0.5592, 0.2871, 0.2378, 0.1329, 0.5600,
          0.8178, 0.0647],
         [0.0169, 0.7674, 0.7118, 0.8773, 0.4374, 0.8725, 0.3074, 0.7249,
          0.7881, 0.6543],
         [0.6792, 0.3034, 0.5508, 0.7957, 0.4235, 0.5739, 0.2011, 0.5102,
          0.3981, 0.8715],
         [0.3627, 0.6890, 0.0282, 0.1049, 0.4376, 0.0926, 0.6134, 0.0876,
          0.9474, 0.8765],
         [0.2154, 0.4543, 0.8528, 0.2172, 0.1806, 0.0410, 0.3770, 0.5955,
          0.8788, 0.3359],
         [0.4602, 0.7980, 0.8473, 0.6866, 0.3778, 0.4206, 0.3405, 0.3209,
          0.2878, 0.5855],
         [0.4086, 0.4868, 0.3015, 0.9135, 0.2007, 0.6177, 0.7487, 0.6281,
          0.9073, 0.8047],
         [0.4677, 0.1356, 0.6503, 0.8423, 0.2203, 0.2629, 0.2616, 0.3347,
          0.7468, 0.2275],
         [0.7345, 0.3535, 0.7180, 0.8108, 0.6079, 0.2967, 0.4805, 0.9921,
          0.8849,

### Zeros and Ones

In [36]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
# Crate a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
ones.dtype # default data type is always float unless explicitly specified

torch.float32

### Creating a range of tensors and tensors-like

returns a 1-D tensor containing a sequence of evenly spaced values within a specified interval (start (inclusive) and end (which is exclusive of the range))

For the range, a step size can be specified to dictate the gap between each value

In [40]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# Use torch.arange()
zero_to_1000 = torch.arange(start=0, end=1000, step=77)
zero_to_1000

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

**_like** suffix is used to create a tensor that mimics the property of another tensor
- `zeros_like`: creates a tensor filled with zeros
- `ones_like`: creates a tensor filled with ones
- `full_like`: creates a tensor filled with a specific scalar value
- `rand_like`: creates a tensor filled with random numbers from a uniform distribution of floating points
- `randn_like`: creates a tensor filled with random numbers from a normal distribution of floating points

In [42]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
ten_fulls = torch.full_like(one_to_ten, 7)  # specify any number other than one/zero
ten_fulls

tensor([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [45]:
ten_normals = torch.randn_like(one_to_ten)
ten_normals

NotImplementedError: "normal_kernel_cpu" not implemented for 'Long'

In [46]:
ten_uniforms = torch.rand_like(one_to_ten)
ten_uniforms

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

The above implementations didn't work because one_to_ten has data type Long/int32 but rand_like and randn_like create of data type float

### Tensor datatypes

**3 big errors when dealing with Tensor data types**
- Tensor not the right datatype
- Tensor not the right shape
- Tensor not the right device

In [47]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = None)

float_32_tensor

tensor([3., 6., 9.])

In [48]:
float_32_tensor.dtype

torch.float32

In [49]:
int_64_tensor = torch.tensor([3, 6, 9],
                              dtype = None)

int_64_tensor

tensor([3, 6, 9])

In [50]:
int_64_tensor.dtype

torch.int64

In [52]:
# change dtype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = None)

float_16_tensor = torch.tensor([3, 6, 9],
                              dtype=torch.float16)

In [53]:
float_16_tensor.dtype

torch.float16

In [54]:
# adding the device and requires_grad parameters
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = None,             # data type of the tensor
                              device = None,            # cpu or cuda, default is None
                              requires_grad = False)    # 

float_32_tensor

tensor([3., 6., 9.])

In [55]:
# convert datatypes
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

#### **Fixing the errors;** `ten_normals` and `ten_uniform`

errors arised because of incorrect datatype.

`torch.randn` and `torch.rand` takes and creates only float32 objects

In [57]:
# check datatype
one_to_ten.dtype

torch.int64

In [58]:
# convert to float32 while feeding to randn_like
ten_normals = torch.randn_like(one_to_ten.type(torch.float32))
ten_normals

tensor([-3.1903,  1.2185, -1.8373, -0.8798, -1.4575,  0.7206,  0.9328, -0.2498,
         0.8718, -0.5361])

In [59]:
# convert to float32 while feeding to rand_like
ten_uniforms = torch.rand_like(one_to_ten.type(torch.float32))
ten_uniforms

tensor([0.0246, 0.2168, 0.0699, 0.4659, 0.6316, 0.4016, 0.1220, 0.1174, 0.7303,
        0.9660])

### Getting Tensor Attributes

In [60]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

**Note**: when performing operations on tensors, make sure the all the tensors are of the same data type. 

Some operations may return an error when data types differ while others don't. Just be mindful of the data types.

float16 * float32 won't error out but in some other operations, the data types would have to be uniform

PyTorch is lenient and uses **type promotion**. When performing an arithmetic operation on two tensors of different data types, the results is automatically promoted to a common data type to prevent data loss. TensorFlow forbids it.

In [62]:
a = torch.tensor([2, 3, 4],
                dtype = torch.int64)

b = torch.tensor([2, 4, 5],
                dtype = torch.float32)

print(a.dtype)
print(b.dtype)

torch.int64
torch.float32


In [65]:
a * b

tensor([ 4., 12., 20.])

#### Most common pitfalls

**Linear Algebra**
- Matrix multiplication
- Dot products

**In-place operations**
- Modifying a tensor in-place with assignment operators (e.g `+=`, `*=`, `.add_()`)

**Note:** just be on the lookout for data type errors and use the right conversion code if you encounter

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to get datatype from a tensor, use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, use `tensor.shape`
3. Tensors not on the right device - to get device from tensor, use `tensor.device`

In [72]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3622, 0.9104, 0.5113, 0.6258],
        [0.8525, 0.0121, 0.1447, 0.2126],
        [0.2819, 0.0274, 0.1157, 0.4113]])

In [75]:
# get tensor data type
some_tensor.dtype

torch.float32

In [76]:
# get shape
some_tensor.shape

torch.Size([3, 4])

In [77]:
# can also use the .size() function to get the shape
some_tensor.size()

torch.Size([3, 4])

In [78]:
# get tensor device information
some_tensor.device

device(type='cpu')

In [82]:
# get all tensor attributes i one place
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3622, 0.9104, 0.5113, 0.6258],
        [0.8525, 0.0121, 0.1447, 0.2126],
        [0.2819, 0.0274, 0.1157, 0.4113]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor operations)

Tensor operations include
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

NN uses these operations to find patterns in dataset through manipulation with these operations

In [83]:
# create tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [84]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [85]:
# subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [86]:
# Try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [87]:
torch.add(tensor, 10)

tensor([11, 12, 13])

**Note** just stick to python arithmetic operators 

In [88]:
# divide
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning
1. Scalar Multiplication
   - Multiplying all the elements of a matrix or vector by a scalar
3. Element-wise multiplicaton : a*b
   - Multiplying the correspinding elements of two matrices or vectors of the same shape (also called the **Hadamard product** or **Schur product**)
4. Multiplication (dot product): `a.b` :
   - Multiplying two vectors of the same length
   - To multiply two matrices, the number of columns in the first matrix must be equal to the number of row in the second matrix (To achieve the equal length paradigm) - inner dimensions must match
     - Multiply rows by columns first to fill first row in new matrix
    
#### 1. Inner dimensions rule
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

#### 2. Resulting matrix has dimensions of outer dimensions
1. `(3, 2) @ (2, 3)` -> `(3, 3)`
2. `(2, 3) @ (3, 3)` -> `(2, 3)`

http://matrixmultiplication.xyz/

In [91]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [92]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [95]:
%%time
# create a for-loop to multiple two tensors and compare the time it uses against torch.matmul
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.59 ms, sys: 1.89 ms, total: 3.48 ms
Wall time: 2.6 ms


In [96]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 602 μs, sys: 0 ns, total: 602 μs
Wall time: 640 μs


tensor(14)

In [97]:
# perform a 3x3 elementwise and matrix multiplication
# create 2 3x3 matrices
first_3by3 = torch.tensor([[2, 3, 4],
                           [6, 5, 4],
                           [9, 8, 1]])

second_3by3 = torch.tensor([[6, 6, 4],
                           [6, 5, 8],
                           [4, 8, 2]])

In [101]:
# elementwise
print(first_3by3 * second_3by3)
print()
print(second_3by3 * first_3by3)

tensor([[12, 18, 16],
        [36, 25, 32],
        [36, 64,  2]])

tensor([[12, 18, 16],
        [36, 25, 32],
        [36, 64,  2]])


In [102]:
# matrix multiplication
print(torch.matmul(first_3by3, second_3by3))
print()
print(torch.matmul(second_3by3, first_3by3))

tensor([[ 46,  59,  40],
        [ 82,  93,  72],
        [106, 102, 102]])

tensor([[ 84,  80,  52],
        [114, 107,  52],
        [ 74,  68,  50]])


**Note**: positioning is important in matrix mulitpication

In [104]:
# @ also works
first_3by3 @ second_3by3

tensor([[ 46,  59,  40],
        [ 82,  93,  72],
        [106, 102, 102]])

### Testing Matrix multiplication rules

In [105]:
torch.matmul(torch.randn(2, 3), torch.randn(2, 3))  # won't work

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [107]:
torch.matmul(torch.randn(2, 2), torch.randn(2, 3))  # will work

tensor([[-0.6806, -1.0303,  1.2601],
        [ 0.4856,  2.2868, -0.3851]])

In [108]:
# the shape
torch.matmul(torch.randn(5, 7), torch.randn(7, 3)).shape

torch.Size([5, 3])

In [111]:
# still on shape errors
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[3, 9],
                         [4, 3],
                         [7, 2]])

In [113]:
tensor_A.shape, tensor_B.shape # check of can be multiplied

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our fix tensor shape issue, we can manipulate one of the tensors using a transpose

A **transpose** switches the axes or dimensions of a given tensor

In [114]:
tensor_B

tensor([[3, 9],
        [4, 3],
        [7, 2]])

In [115]:
tensor_B.T, tensor_B.T.shape

(tensor([[3, 4, 7],
         [9, 3, 2]]),
 torch.Size([2, 3]))

In [117]:
torch.matmul(tensor_B, tensor_B.T) # inner dimensions now the same, outer dimensions now product

tensor([[90, 39, 39],
        [39, 25, 34],
        [39, 34, 53]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

Aggregation means, going from a large amount of numbers to a small amount

In [118]:
# create a tensor
x = torch.tensor([0, 100, 2000])
x

tensor([   0,  100, 2000])

In [120]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [121]:
# find max
torch.max(x), x.max()

(tensor(2000), tensor(2000))

In [131]:
# find the mean
torch.mean(x, dtype=torch.float32) 

# the torch.mean function takes only floating point or complex dtype, no integers

tensor(700.)

In [130]:
torch.mean(x.type(torch.float32))

tensor(700.)

In [132]:
# find the sum
torch.sum(x), x.sum()

(tensor(2100), tensor(2100))