## GETTING STARTED WITH PYTORCH FUNDAMENTALS

#### **INSTALLATION**

In [2]:
# install pytorch for cpu
!pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.3/192.3 MB 7.1 MB/s eta 0:00:00m eta 0:00:010:00:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 11.6 MB/s eta 0:00:00m eta 0:00:010:0101
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.4/203.4 kB 5.1 MB/s eta 0:00:00 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 10.0 MB/s eta 0:00:00m eta 0:00:010:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 14.3 MB/s eta 0:00:00m eta 0:00:01


In [2]:
import torch

In [3]:
# test pytorch
mat = torch.randn(5, 3)
print(mat)

tensor([[ 0.1436, -0.9094, -1.4191],
        [-0.4945,  1.3832, -3.1505],
        [-0.1672,  0.0944,  1.1478],
        [ 0.5119,  1.0322, -2.1636],
        [-0.8626, -0.0205,  0.2867]])


## Introduction to Tensors

### Creating Tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim # scalar has 0-dimensions

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# vector: has magnitude (how far) and direction (which way)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [17]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                          [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
 TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

> up there, we've got a 1 three by three tensor </br>
> Naming convention: scalar and vector: lower case vars, matrix and tensors: UPPER CASE VARS

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update`

In [35]:
# Create a random tensor of size (3, 4)
# command: torch.rand
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3731, 0.1076, 0.9271, 0.1437],
        [0.2583, 0.3707, 0.1761, 0.8553],
        [0.8214, 0.4756, 0.9291, 0.3258]])

In [31]:
# Create a random tensor with similar shape to an image tensor
random_iamge_size_tensor = torch.rand(size=(3, 224, 224)) # color channels, height: cc (R, G, B)
random_iamge_size_tensor.shape, random_iamge_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [30]:
random_tensor_exercise = torch.rand(10, 10, 10)
random_tensor_exercise

tensor([[[0.5460, 0.8582, 0.7133, 0.5770, 0.3198, 0.3301, 0.7150, 0.3583,
          0.8055, 0.3446],
         [0.2533, 0.5959, 0.5937, 0.2226, 0.9372, 0.7924, 0.0132, 0.9872,
          0.4139, 0.7498],
         [0.3615, 0.8514, 0.3678, 0.9839, 0.8745, 0.2523, 0.2590, 0.6565,
          0.6104, 0.9211],
         [0.4795, 0.3901, 0.5100, 0.2427, 0.6303, 0.6048, 0.2000, 0.7721,
          0.8206, 0.8329],
         [0.2845, 0.2970, 0.9319, 0.9814, 0.7507, 0.9026, 0.0880, 0.5477,
          0.3879, 0.1746],
         [0.3030, 0.2097, 0.8183, 0.9827, 0.8442, 0.3488, 0.0205, 0.3975,
          0.8815, 0.8436],
         [0.7728, 0.8947, 0.2570, 0.3956, 0.4042, 0.8064, 0.6564, 0.9856,
          0.3287, 0.2435],
         [0.9023, 0.7066, 0.7374, 0.7772, 0.6514, 0.2126, 0.6921, 0.7056,
          0.5602, 0.6233],
         [0.2324, 0.6228, 0.0807, 0.5097, 0.1611, 0.1732, 0.1815, 0.1233,
          0.2846, 0.6974],
         [0.7626, 0.4533, 0.7628, 0.0599, 0.7197, 0.4618, 0.5312, 0.2051,
          0.3120,

### Zeros and Ones

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Crate a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype # default data type is always float unless explicitly specified

torch.float32

### Creating a range of tensors and tensors-like

In [47]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# Use torch.arange()
zero_to_1000 = torch.arange(start=0, end=1000, step=77)
zero_to_1000

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [50]:
# Creating tensors like
# create a tensor to take the shape of an already existing tensor
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes