In [1]:
import torch

In [2]:
# create a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([2, 5])
print(vector.shape)
print(vector.size())
print(vector.ndim)

torch.Size([2])
torch.Size([2])
1


In [6]:
MATRIX = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8]])

MATRIX

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [7]:
print(MATRIX.size())
print(MATRIX.shape)
print(MATRIX.ndim)

torch.Size([2, 4])
torch.Size([2, 4])
2


In [8]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [9]:
print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([1, 3, 3])
3


In [10]:
# let's create a 3x3x3 TENSOR
# that would be something like RGB color channel with 3 layers, and each layer having 3x3 pixels
TENSOR_RGB = torch.tensor([[[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]],
                           [[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]],
                            [[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]]
                          ])

TENSOR_RGB

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
print(TENSOR_RGB.ndim)
print(TENSOR_RGB.shape)

3
torch.Size([3, 3, 3])


**MY INTUITION FOR CREATING N-DIMENSIONAL ARRAYS AND TENSORS**

- The `square bracket` theory
  - **Scalars** are created with no square bracket     : `torch.tensor()`
    - 0 dimensions
  - **Vectors** are created with one square bracket    : `torch.tensor([])`
    - square bracket contains `scalars`
    - 1 dimension: takes only rows, or only columns
  - **MATRICES** are created with two square brcakets  : `torch.tensor([  []  ])`
    - square brackets contains `vectors`
    - 2 dimensions: takes both rows and columns
  - **TENSORS** are created with three square brackers : `torch.tensor([ [[]] ])`
    - square bracket contains `matrices`
    - 3 dimensions: takes multiple layers for each matrix

In [12]:
# create tensor with zeros
zeros = torch.zeros([2, 5]) # default data type is float32
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [13]:
# create tensor with ones
ones = torch.ones([5, 5])
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:
# create a tensor and initialize with random numbers
random_tensor = torch.randn([5, 5])  # initializes with standard normally distributed numbers
random_tensor

tensor([[-0.0142, -0.6361, -0.3253,  0.9067, -1.0710],
        [-0.4751,  0.3703, -1.4483, -0.5980,  1.0592],
        [-1.8380, -0.6404, -0.9553, -1.0388, -1.0057],
        [-2.6407, -1.4712, -1.3199, -0.5886,  0.6472],
        [ 0.3368, -0.9492, -0.4307,  0.0363, -1.0235]])

In [15]:
# create 5x5x5 random tensor
random3by3 = torch.randn(5, 5, 5)
random3by3

tensor([[[ 0.5045, -0.7787,  1.1361, -1.2351, -0.5312],
         [ 1.6717, -1.1250,  0.7179, -0.9048,  2.1255],
         [ 0.1788, -0.5372, -0.3268,  0.1802,  0.1836],
         [ 0.2642,  0.1892, -0.3813, -0.2920, -0.9387],
         [-0.1040,  0.0204, -0.7478, -0.5416,  1.0735]],

        [[-1.3074, -0.2539,  0.0911,  0.2933,  0.8982],
         [-2.3010,  0.7427,  0.3568, -0.4161,  0.8618],
         [ 0.1598,  0.7833,  0.7146,  0.9916,  0.9366],
         [ 0.7123,  0.1947, -1.8864,  2.5227,  0.3028],
         [-0.0740, -1.1039, -0.1822, -0.2958,  0.7919]],

        [[ 1.1204, -0.7397, -0.7049,  1.0798, -0.5290],
         [-0.3663,  0.1412,  0.4791, -0.3801,  1.4274],
         [ 1.5837,  0.4565,  0.3116, -0.8352, -1.5673],
         [ 0.8785, -0.6756, -0.1497,  0.4800, -0.7136],
         [-0.2535, -0.7102,  1.4912,  0.3630,  2.5524]],

        [[-0.9154, -0.3376, -0.5104, -0.6023, -0.2072],
         [ 1.0739,  0.9265, -1.2385,  0.2854, -0.4980],
         [-0.5788,  0.7634,  0.6623,  0.06